// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.5.1
// source: message/msg.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Initialized  -- call after actor new
type Initialize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Initialize) Reset() {
	*x = Initialize{}
	mi := &file_message_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Initialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialize) ProtoMessage() {}

func (x *Initialize) ProtoReflect() protoreflect.Message {
	mi := &file_message_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialize.ProtoReflect.Descriptor instead.
func (*Initialize) Descriptor() ([]byte, []int) {
	return file_message_msg_proto_rawDescGZIP(), []int{0}
}

//Poison -- will stop a actor
type Poison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poison) Reset() {
	*x = Poison{}
	mi := &file_message_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poison) ProtoMessage() {}

func (x *Poison) ProtoReflect() protoreflect.Message {
	mi := &file_message_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poison.ProtoReflect.Descriptor instead.
func (*Poison) Descriptor() ([]byte, []int) {
	return file_message_msg_proto_rawDescGZIP(), []int{1}
}

//Error --
type ErrCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Des           string                 `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrCode) Reset() {
	*x = ErrCode{}
	mi := &file_message_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrCode) ProtoMessage() {}

func (x *ErrCode) ProtoReflect() protoreflect.Message {
	mi := &file_message_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrCode.ProtoReflect.Descriptor instead.
func (*ErrCode) Descriptor() ([]byte, []int) {
	return file_message_msg_proto_rawDescGZIP(), []int{2}
}

func (x *ErrCode) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrCode) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

//Subscribe -- for event_stream
type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_message_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_message_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_message_msg_proto_rawDescGZIP(), []int{3}
}

func (x *Subscribe) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Subscribe) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

//Unsubscribe -- form event_stream
type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_message_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_message_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_message_msg_proto_rawDescGZIP(), []int{4}
}

func (x *Unsubscribe) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Unsubscribe) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

var File_message_msg_proto protoreflect.FileDescriptor

const file_message_msg_proto_rawDesc = "" +
	"\n" +
	"\x11message/msg.proto\x12\amessage\"\f\n" +
	"\n" +
	"Initialize\"\b\n" +
	"\x06Poison\"/\n" +
	"\aErrCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03des\x18\x02 \x01(\tR\x03des\"C\n" +
	"\tSubscribe\x12\x18\n" +
	"\aactorId\x18\x01 \x01(\tR\aactorId\x12\x1c\n" +
	"\teventName\x18\x02 \x01(\tR\teventName\"E\n" +
	"\vUnsubscribe\x12\x18\n" +
	"\aactorId\x18\x01 \x01(\tR\aactorId\x12\x1c\n" +
	"\teventName\x18\x02 \x01(\tR\teventNameB#Z!github.com/chenxyzl/grain/messageb\x06proto3"

var (
	file_message_msg_proto_rawDescOnce sync.Once
	file_message_msg_proto_rawDescData []byte
)

func file_message_msg_proto_rawDescGZIP() []byte {
	file_message_msg_proto_rawDescOnce.Do(func() {
		file_message_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_msg_proto_rawDesc), len(file_message_msg_proto_rawDesc)))
	})
	return file_message_msg_proto_rawDescData
}

var file_message_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_msg_proto_goTypes = []any{
	(*Initialize)(nil),  // 0: message.Initialize
	(*Poison)(nil),      // 1: message.Poison
	(*ErrCode)(nil),     // 2: message.ErrCode
	(*Subscribe)(nil),   // 3: message.Subscribe
	(*Unsubscribe)(nil), // 4: message.Unsubscribe
}
var file_message_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_msg_proto_init() }
func file_message_msg_proto_init() {
	if File_message_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_msg_proto_rawDesc), len(file_message_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_msg_proto_goTypes,
		DependencyIndexes: file_message_msg_proto_depIdxs,
		MessageInfos:      file_message_msg_proto_msgTypes,
	}.Build()
	File_message_msg_proto = out.File
	file_message_msg_proto_goTypes = nil
	file_message_msg_proto_depIdxs = nil
}
