// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.5.1
// source: remote/remote.proto

package remote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//    enum MsgType {
	//        Tell = 0;
	//        Ask = 1;
	//        Reply = 2;
	//    }
	Header        map[string]string `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //for context k.v
	Sender        string            `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Target        string            `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	MsgSnId       uint64            `protobuf:"varint,4,opt,name=msgSnId,proto3" json:"msgSnId,omitempty"`
	MsgName       string            `protobuf:"bytes,5,opt,name=msgName,proto3" json:"msgName,omitempty"`
	Content       []byte            `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Error         string            `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"` //for reply error immediately? else waiting timeout too slow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_remote_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_remote_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_remote_remote_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Envelope) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Envelope) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Envelope) GetMsgSnId() uint64 {
	if x != nil {
		return x.MsgSnId
	}
	return 0
}

func (x *Envelope) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Envelope) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Envelope) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_remote_remote_proto protoreflect.FileDescriptor

const file_remote_remote_proto_rawDesc = "" +
	"\n" +
	"\x13remote/remote.proto\x12\x06remote\"\x8f\x02\n" +
	"\bEnvelope\x124\n" +
	"\x06header\x18\x01 \x03(\v2\x1c.remote.Envelope.HeaderEntryR\x06header\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x18\n" +
	"\amsgSnId\x18\x04 \x01(\x04R\amsgSnId\x12\x18\n" +
	"\amsgName\x18\x05 \x01(\tR\amsgName\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012>\n" +
	"\bRemoting\x122\n" +
	"\x06Listen\x12\x10.remote.Envelope\x1a\x10.remote.Envelope\"\x00(\x010\x01B\"Z github.com/chenxyzl/grain/remoteb\x06proto3"

var (
	file_remote_remote_proto_rawDescOnce sync.Once
	file_remote_remote_proto_rawDescData []byte
)

func file_remote_remote_proto_rawDescGZIP() []byte {
	file_remote_remote_proto_rawDescOnce.Do(func() {
		file_remote_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_remote_proto_rawDesc), len(file_remote_remote_proto_rawDesc)))
	})
	return file_remote_remote_proto_rawDescData
}

var file_remote_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_remote_remote_proto_goTypes = []any{
	(*Envelope)(nil), // 0: remote.Envelope
	nil,              // 1: remote.Envelope.HeaderEntry
}
var file_remote_remote_proto_depIdxs = []int32{
	1, // 0: remote.Envelope.header:type_name -> remote.Envelope.HeaderEntry
	0, // 1: remote.Remoting.Listen:input_type -> remote.Envelope
	0, // 2: remote.Remoting.Listen:output_type -> remote.Envelope
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_remote_remote_proto_init() }
func file_remote_remote_proto_init() {
	if File_remote_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_remote_proto_rawDesc), len(file_remote_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_remote_proto_goTypes,
		DependencyIndexes: file_remote_remote_proto_depIdxs,
		MessageInfos:      file_remote_remote_proto_msgTypes,
	}.Build()
	File_remote_remote_proto = out.File
	file_remote_remote_proto_goTypes = nil
	file_remote_remote_proto_depIdxs = nil
}
